import { db } from '@/lib/firebase';
import {
    collection,
    query,
    getDocs,
    writeBatch,
    doc,
    setDoc,
    serverTimestamp
} from 'firebase/firestore';

export type ArchiveResult = {
    success: boolean;
    archivedCount: {
        bills: number;
        expenses: number;
        deposits: number;
    };
    error?: string;
};

/**
 * Archives all current data to a monthly archive document and clears the main collections.
 * @param periodName - The name of the period to archive (e.g., "2024-01", "January 2024")
 * @param carryOverAmount - The amount to carry forward to the next month
 * @param nextPeriodStart - The start date of the next period (YYYY-MM-DD)
 * @param adminDetails - Details of the admin performing the action
 * @returns Result object with counts
 */
export const archiveMonth = async (
    periodName: string,
    carryOverAmount: number,
    nextPeriodStart: string,
    adminDetails: { uid: string; name: string; avatar: string }
): Promise<ArchiveResult> => {
    try {
        // 1. Fetch all data to be archived
        const billsSnapshot = await getDocs(collection(db, 'bills'));
        const expensesSnapshot = await getDocs(collection(db, 'expenses'));
        const depositsSnapshot = await getDocs(collection(db, 'deposits'));

        const billsData = billsSnapshot.docs.map(d => ({ ...d.data(), originalId: d.id }));
        const expensesData = expensesSnapshot.docs.map(d => ({ ...d.data(), originalId: d.id }));
        const depositsData = depositsSnapshot.docs.map(d => ({ ...d.data(), originalId: d.id }));

        // 2. Archive Metadata Batch (Create Archive Doc + Create Opening Balance)
        const metaBatch = writeBatch(db);

        // Create Archive Document
        const archiveRef = doc(collection(db, 'archivedMonths'), periodName);
        metaBatch.set(archiveRef, {
            period: periodName,
            archivedAt: serverTimestamp(),
            data: {
                bills: billsData,
                expenses: expensesData,
                deposits: depositsData
            },
            summary: {
                totalBills: billsData.length,
                totalExpenses: expensesData.length,
                totalDeposits: depositsData.length,
                carriedOverBalance: carryOverAmount
            }
        });

        // Create "Opening Balance" deposit for the new month
        if (carryOverAmount > 0) {
            const newDepositRef = doc(collection(db, 'deposits'));
            metaBatch.set(newDepositRef, {
                uid: 'system',
                userName: 'FlatFund System',
                userAvatar: 'FS',
                amount: carryOverAmount,
                date: nextPeriodStart,
                month: nextPeriodStart.substring(0, 7), // YYYY-MM
                note: `Opening Balance from ${periodName}`,
                status: 'confirmed',
                isAutoGenerated: true,
                createdAt: serverTimestamp(),
                updatedAt: serverTimestamp()
            });
        }

        // Commit the metadata batch first
        await metaBatch.commit();

        // 3. Batch Deletions in chunks (Firestore limit is 500 ops per batch)
        // We use a safe limit of 400 to leave room for overhead if any
        const BATCH_SIZE = 400;
        const allDocsToDelete = [
            ...billsSnapshot.docs,
            ...expensesSnapshot.docs,
            ...depositsSnapshot.docs
        ];

        for (let i = 0; i < allDocsToDelete.length; i += BATCH_SIZE) {
            const deleteBatch = writeBatch(db);
            const chunk = allDocsToDelete.slice(i, i + BATCH_SIZE);

            chunk.forEach(docSnapshot => {
                deleteBatch.delete(docSnapshot.ref);
            });

            await deleteBatch.commit();
        }

        return {
            success: true,
            archivedCount: {
                bills: billsData.length,
                expenses: expensesData.length,
                deposits: depositsData.length
            }
        };

    } catch (error: any) {
        console.error("Archiving failed:", error);
        return {
            success: false,
            archivedCount: { bills: 0, expenses: 0, deposits: 0 },
            error: error.message
        };
    }
};
